[filetype.directory]
mimes = ["inode/directory"]

[filetype.markdown]
extensions = ["md"]

[filetype.patch]
mimes = ["text/x-patch"]

[filetype.pdf]
mimes = ["application/pdf"]

[filetype.text]
mimes = [
    "text",
    "application/pkcs8+pem",
    "application/x-perl",
    "application/x-php",
    "application/x-shellscript",
    "application/x-subrip",
    "application/xml"
]

[filetype.xsv]
extensions = ["csv", "tsv"]

# File handlers
#
# - command
# The command to run to open or preview file.
# Substitution is done for the following expressions:
#   %c: terminal column count
#   %i: input path
#   %l: terminal line count
#   %m: input MIME type
# Use '%%' if you need to pass a literal '%' char.
#
# - shell
# If true, runs the command in a shell, use this if you use pipes. Defaults to false.
#
# - wait
# If true, waits for the handler to exit. Defaults to true.
#
# - no_pipe
# If true, disable piping data to handler's stdin, and use a slower temporary file instead if data is piped to rsop.
# Incompatible with 'wait = false'. Defaults to false.
#
# - stdin_arg
# When previewing or opening data from stdin, with what string to substitute '%i'. Defaults to "-", some programs require "".
#

[default_handler_preview]
command = "echo '🔍 MIME: %m'; head -n $((%l - 1))"
shell = true
stdin_arg = ""

[default_handler_open]
command = "less -R"
shell = true
stdin_arg = ""

[handler_preview.directory]
command = "eza -alFh --tree --level 2 --color=always --icons=always %i | head -n %l"
shell = true

[handler_open.directory]
command = "eza -alFh --tree --level 2 --color=always --icons=always %i | less -R"
shell = true

[handler_preview.markdown]
command = "themed-bat --paging=never --terminal-width=%c %i"

[handler_preview.patch]
command = "themed-bat --paging=never --terminal-width=%c %i"

[handler_preview.text]
command = "themed-bat --paging=never --terminal-width=%c %i"

[handler_preview.xsv]
command = "themed-bat --paging=never --terminal-width=%c --language=csv %i"

[handler_open.text]
command = "nvim %i"

[handler_open.xsv]
command = "nvim %i"
no_pipe = true

[handler_edit.markdown]
command = "nvim %i"
wait = false

[handler_open.pdf]
command = "open Preview %i"
no_pipe = true

[handler_open.svg]
command = "browser %i"
no_pipe = true

# Filters
#
# Filters are special handlers that process their input and send their output either to another filter or to a final handler.
# They are typically useful to transparently decompress files like .log.xz, .pcapng.gz, tar.gz, etc.
# but you can also use it for more specific needs like converting some document formats to markdown and then using your usual handler
# for markdown files to preview or open it.
# Filter configuration parameters are similar to handler, except wait that is implied as true.

# Scheme handlers

[handler_scheme.http]
command = "browser %i"

[handler_scheme.https]
command = "browser %i"
